### ISSUE TITLE
Minecraftapks reposted my mod. What can I do ?

### ISSUE THREAD

**Issue by Aang23** [StopModReposts/Illegal-Mod-Sites#139]
I have recently started working on a mod, RealSerene. While recently searching on the web to see if anyone spoke about it, or reposted it, I found this website : https://www.minecraftapks.com/real-serene-mod/#comment-84 , which reposted it.
They used the original description, (see here : https://minecraft.curseforge.com/projects/realserene).

Do you know what I can do ? I tested the jar they distribute and the MD5 is not the same.

**Comment by bilde2910** [comment]
Thanks for the submission. The site was added. I couldn't reproduce the integrity mismatch issue though, if you have an example that's live now, I'd love to take a look.

**Comment by Aang23** [comment]
This isn't the case for this mod, I'm gonna take a look, and inform you a soon as possible.
