### ISSUE TITLE
Merge with AntiModRepost

### ISSUE THREAD

**Issue by bilde2910** [StopModReposts/Illegal-Mod-Sites#140]
Add missing sites from contributor project [AntiModRepost](https://berrysauce.github.io/AntiModRepost/) by @berrysauce 

+ minecraft-installer de
+ gamefiles de
+ fileplanet com
+ minecraftdls com
+ o-crafte ru

**Comment by berrysauce** [comment]
Made a spreadsheet after all...

Here are some sites I also found today:
https://docs.google.com/spreadsheets/d/10awWGV9BsfQF234OEPIe24w_6d3SBSyVyGAq-YOw9Sc

**Comment by bilde2910** [comment]
The sites have all been added, except for `modsforminecraft com` which, as far as I could see, used original downloads.
