### ISSUE TITLE
geroncraft

### ISSUE THREAD

**Issue by RedstoneParadox** [StopModReposts/Illegal-Mod-Sites#149]
http://www.geroncraft.ru/ not only rehosts mods but also rehosts texture packs and data packs, not to mention that a lot of the images of stuff appear to be misleading.

**Comment by bilde2910** [comment]
Thanks for the submission. I could not find redistribution here (all pages I checked used CurseForge downloads), but I added it on the grounds of advertising and misleading users. If you have an example of a redistributed mod, please let me know and I'll gladly revisit my rating.
