### ISSUE TITLE
www.minecrafttube.net

### ISSUE THREAD

**Issue by P3pp3rF1y** [StopModReposts/Illegal-Mod-Sites#150]
The site has lots of ads, claims to have mods for versions they haven't been updated to (even 1.13.1 forge mods already yet there is no forge for 1.13), most of the time many clicks just open advertisement popups and "download" links seem to only open more popups.
Not sure that I would consider it repost based on the fact that i don't seem to be able to download any mod, but certainly a site I don't want to see in my search results when searching for mods they "have" on their site.
https://www.minecrafttube.net/thermal-expansion-mod/

**Comment by Flipp3rrr** [comment]
Wahaha, I wanted to check it out but my virus-scanner just blocks it!

**Comment by bilde2910** [comment]
Thanks for the report and sorry for the delayed reply to this issue. There's definitely sketchy stuff going on at that site. Adding it shortly.
