### ISSUE TITLE
minecraft11.com

### ISSUE THREAD

**Issue by eatYourHashs** [StopModReposts/Illegal-Mod-Sites#151]
This site reposts mods and datapacks, and also distributes cracked launchers and resource packs including X-ray packs. I had a datapack I made (RPG Skills) be reposted on here; the text and one image were copied straight from PMC, and the version was weeks old.

**Comment by bilde2910** [comment]
Thanks for submitting the site, and sorry for the delayed reply. This site will be added to the list shortly.
