### ISSUE TITLE
The truth about redistributing mods

### ISSUE THREAD

**Issue by migdyn** [StopModReposts/Illegal-Mod-Sites#152]
The ones who write mods should be happy that someone else redistributes them. I don't really understand the purpose of this campaign. But yeah, this is why I stopped playing Minecraft about a year ago. Because of people like you. Why are you even using GitHub - which doesn't work without the huge amount of JavaScript.

**Comment by bl4ckscor3** [comment]
Us modders are not happy because they're redistributing the mods without crediting the original owner or actually using the original download links. Latter does not generate any income for the modder and, believe it or not, for some this income is very important.
