### ISSUE TITLE
https://www.planetminecraft.com Misleading

### ISSUE THREAD

**Issue by UserElf** [StopModReposts/Illegal-Mod-Sites#153]
Current MC Forge Versions: https://prnt.sc/lfw0nj
The mods on planetminecraft.com: https://www.planetminecraft.com/resources/mods/?op1=47

**Comment by UserElf** [comment]
There is no MC Forge version for the 1.13 MC versions.

**Comment by Matts** [comment]
Forge is not the only mod framework, besides, people call 'data packs' mods these days. The staff of PMC is active and fair enough to prevent mod reposts.

I object against this issue.

**Comment by mchorse** [comment]
Besides, PMC uses mods section for external programs and tools, and also **the original authors** post mods there. It's not a repost website.
