### ISSUE TITLE
http://mcpedl.com/

### ISSUE THREAD

**Issue by Flipp3rrr** [StopModReposts/Illegal-Mod-Sites#165]
I was browsing around and found this site. I saw it was already reported. My virus scanner marked the download of the following add-on as dangerous: http://mcpedl.com/butterfly-s-mods/

**Comment by RedstoneParadox** [comment]
MCPEDL is a legitimate and well-known site for sharing content related to Bedrock Edition. I can't vouch for the validity of that add-on in particular, though.

**Comment by bilde2910** [comment]
Previously determined to be a reputable site (#71), and we won't let one mod result in the whole site being listed. I haven't checked the addon you linked, but you can probably reach out to the site administration if you're worried about it.
