### ISSUE TITLE
New Sites to add

### ISSUE THREAD

**Issue by berrysauce** [StopModReposts/Illegal-Mod-Sites#175]
Here are some sites which mostly repost PE mods/addons:
- fmcpe.com
- mods.mc-pe.net
- mcpefl.com

They all have mod downloads running from their own servers.

**Comment by Flipp3rrr** [comment]
They indeed repost all of them, at least they're malware free according to VirusTotal.

**Comment by AlexejheroYTB** [comment]
https://mcpefl.com/ is erroring for me
