### ISSUE TITLE
New sites

### ISSUE THREAD

**Issue by marcus8448** [StopModReposts/Illegal-Mod-Sites#177]
Geroncraft ru

**Comment by marcus8448** [comment]
Geroncraft does not link to the original source and is a pure curseforge rip off.

**Comment by Flipp3rrr** [comment]
That means it's not eligible to be added to the list, as long as there's no malware and repost involved.

**Comment by Flipp3rrr** [comment]
Looks like this site _**reposted**_ Fabric into an installer at `hxxps://www.geroncraft.ru/fabric/`. I'm not sure though because I don't speak Russian.

**Comment by Flipp3rrr** [comment]
According to [VirusTotal](https://www.virustotal.com/#/url/0b7ee9b1bf540901a8f5cfafccd3a732721c7aad42aa80da5fcc2420692ac87c/detection) it doesn't contain malware.
