### ISSUE TITLE
new site

### ISSUE THREAD

**Issue by Tree54621** [StopModReposts/Illegal-Mod-Sites#180]
resourcepackstexture.com

**Comment by beanaboston** [comment]
Doesn't seem to be actually hosting anything. However does seem to have redirecting issues for the link. For my phone at least. Clicking download link redirects to different site, asks for notification permission. Click deny, then repeat.

**Comment by beanaboston** [comment]
Okay. Soo maybe only sometimes issue with redirect, was able to confirm that at least one sphax it links to proper source. But does NOT link to proper source for optifine. So maybe?
