### ISSUE TITLE
New site: loveminecraft.com

### ISSUE THREAD

**Issue by hypehuman** [StopModReposts/Illegal-Mod-Sites#182]
Claims to have download links for Forge 1.14 and 1.14.1, which don't exist yet. The links just take you to an ad.

**Comment by Flipp3rrr** [comment]
I was just going to report this `hxxps://loveminecraft.com/minecraft-forge/`!

**Comment by TheRealWormbo** [comment]
That site also distributes other mods (like BuildCraft or Twilight Forest) supposedly upgraded for 1.14.4, including neat-looking images to look like a legit website.

**Comment by AlexejheroYTB** [comment]
Linked: https://modsfire.download/
