### ISSUE TITLE
New site to add - Planet LemonCraft

### ISSUE THREAD

**Issue by thepwrtank18** [StopModReposts/Illegal-Mod-Sites#220]
https://planetlemoncraft.com/

Advertises mods that don't exist (such as OptiFine 1.15 as of creation) and uploads malware/adware.

**Comment by berrysauce** [comment]
Links to https://minecraft-dl.com

**Comment by berrysauce** [comment]
Fixed in #317

**Comment by thepwrtank18** [comment]
i completely forgot this issue existed lol
