### ISSUE TITLE
New site to add: https://www.minecraftmods.com/

### ISSUE THREAD

**Issue by McJoe21** [StopModReposts/Illegal-Mod-Sites#235]
**What site do you want to be added?**
https://www.minecraftmods.com/

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft

**Do you have anything else worth mentioning?**
Broken Curseforge downloads

**Comment by berrysauce** [comment]
Working links + mentioned authors. If an author takes down their mod or the link changes over time these errors can happen.
