### ISSUE TITLE
Site to consider removing - Softonic

### ISSUE THREAD

**Issue by spokrr** [StopModReposts/Illegal-Mod-Sites#288]
Softonic is not a minecraft mod reposting site. Although there are minecraft mods on there, there are also millions of legitimate or semi-legitimate programs distributed through Softonic. Having a massive pop-up block your screen is insanely annoying when trying to download say Hamachi or any other software from Softonic. Please consider removing it from the list, or even just having a smaller popup saying "Warning" and something about reposted mods. Thanks!

**Comment by Beatso** [comment]
with a quick glance at the website, https://minecraft.en.softonic.com/ downloads malware. this isn't a legit download.

**Comment by berrysauce** [comment]
Normally we give out side-wide warnings but it might be possible to only blacklist the Minecraft subdomain of Softonic. I'd still generally don't recommend to download from them.

**Comment by dada513** [comment]
im against removing softonic. They have lots of malware. Although mods arent the only thing there, reposting software is the same thing. Download from the developer, not softonic

**Comment by dada513** [comment]
[#9](https://github.com/StopModReposts/Extension/issues/9) related - wont annoy as much if you disable that setting. Also it now remembers you ignored the site until browser restart

**Comment by dada513** [comment]
Closing as extension now remembers your choice, and softonic is just generally a malicious site even outside of Minecraft
