### ISSUE TITLE
New site to add: https://amodsus.com/

### ISSUE THREAD

**Issue by lividhen** [StopModReposts/Illegal-Mod-Sites#365]
**What site do you want to be added?**

https://amodsus.com/

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)

Among Us

**Do you have anything else worth mentioning?**

People are re-uploading paid mods

**Comment by SiriHackYT** [comment]
All the modes are free of access and credited, if a paying mod appears for free it is deleted by the moderation

**Comment by lividhen** [comment]
> All the mods are free of access and credited, if a paying mod appears for free it is deleted by the moderation

Oh, there were a few that weren't at one point, guess they got it all figured out, my bad.
