### ISSUE TITLE
Evaluate mcpedl.com

### ISSUE THREAD

**Issue by dada513** [StopModReposts/Illegal-Mod-Sites#426]
MCPEDL has always been in some issues. I'm not sure

@StopModReposts/list-maintainers

**Comment by Brandonbr1** [comment]
one thing to note is that they do review the things that the people that they submit but i did still find some reposted stuff on mcpedl.com

the og map:[https://mcpedl.com/2p-pvp-arena/]https://www.planetminecraft.com/project/2p-pvp-arena/
reposted map:[https://mcpedl.com/2p-pvp-arena/](https://mcpedl.com/2p-pvp-arena/)

**Comment by berrysauce** [comment]
Putting this report on hold since we need more time to evaluate the site. If anyone has anything to share about this report, please comment below.

**Comment by Brandonbr1** [comment]
PlantetMinecraft allows it as a suitable host 
![mcpedl comnodelete](https://user-images.githubusercontent.com/74426342/148861676-22065754-4089-40c4-87e7-710b1e8c24ee.PNG)

**Comment by Brandonbr1** [comment]
@berrysauce  i spent time search through this website and not a single one addon i found a repost

**Comment by dada513** [comment]
I believe this should be rejected from the data gathered in this issue
