### ISSUE TITLE
New site to add: [www.nexusmods.com]

### ISSUE THREAD

**Issue by Brandonbr1** [StopModReposts/Illegal-Mod-Sites#433]
**What site do you want to be added?**
www.nexusmods.com

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Subnautica

**Do you have anything else worth mentioning?**
no

**Comment by MaowImpl** [comment]
Nexus is a mod uploads site, not a mod reposts site.
Files are uploaded by users who have accounts on the site.
It is also used legitimately by some game communities as a sort of Steam Workshop alternative, since some games are cross-store (example: Hacknet)
