### ISSUE TITLE
New site to add: [www.minecraft-france.fr]

### ISSUE THREAD

**Issue by Brandonbr1** [StopModReposts/Illegal-Mod-Sites#449]
**What site do you want to be added?**

https://www.minecraft-france.fr/optifine/

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft

**Do you have anything else worth mentioning?**
No

**Comment by berrysauce** [comment]
Has been rejected multiple times, see #95, #216, #222
