### ISSUE TITLE
New site to add: nowmods.com

### ISSUE THREAD

**Issue by berrysauce** [StopModReposts/Illegal-Mod-Sites#462]
Review nowmods.com in detail, especially for Stardew Valley

**Comment by Brandonbr1** [comment]
seems to steal mods from nexusmods.com

**Comment by Brandonbr1** [comment]
i have checked through 1 page on Stardew Valley and  seems bad so far science all of them are reposts

**Comment by Brandonbr1** [comment]
checked through all the 3 pages in Stardew Valley and all of them are reposts
