### ISSUE TITLE
Hosts file is empty.

### ISSUE THREAD

**Issue by cheatfreak47** [StopModReposts/Illegal-Mod-Sites#469]
Your hosts file seems to be busted. It has no entries. 
https://api.varden.info/smr/hosts.php

**Comment by Brandonbr1** [comment]
that is not the host file i think that is the old host file

here is the new host [https://api.stopmodreposts.org/hosts.txt](file:https://api.stopmodreposts.org/hosts.txt)

**Comment by dada513** [comment]
like @Brandonbr1, the host file in the mentioned URL is from the outdated API.

**Comment by cheatfreak47** [comment]
Ah okay, gotcha.

**Comment by cheatfreak47** [comment]
Also, if possible, the old url should redirect to the new ones, if the old host doesn't mind hosting the redirect.

**Comment by dada513** [comment]
I think it's from the other team member's site

**Comment by Brandonbr1** [comment]
> I think it's from the other team member's site

I pretty sure it is from [bilde2910](https://github.com/bilde2910)
