### ISSUE TITLE
New site to add: A couple illegal redistribution (piracy) websites

### ISSUE THREAD

**Issue by xXmartin0311** [StopModReposts/Illegal-Mod-Sites#476]
**What site do you want to be added?**

crystal-launcher.net
launchershiginima.com
salwyrr.com

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)

Minecraft

**Do you have anything else worth mentioning?**
All 3 of these sites distribute cracked version of minecraft, and could possibly contain malware

**Comment by Brandonbr1** [comment]
@xXmartin0311 

launchershiginima.com does not repost mods it links back to the curseforge so it is not a repost but it does pirate a launcher a launcher so idk

**Comment by Brandonbr1** [comment]
http://crystal-launcher.net/p/modpacks cant see any downloads

**Comment by xXmartin0311** [comment]
well, they do illegally redistribute something, which is minecraft. I thnik it still applies

**Comment by Brandonbr1** [comment]
@berrysauce  can  illegal/cracked  Minecraft launchers  be put on the list?😀

**Comment by dada513** [comment]
> @berrysauce @dada513   can  illegal/cracked  Minecraft launchers  be put on the list?😀

I believe yes as we have lots of pirate sites on the list
