### ISSUE TITLE
New site to add: mcmodspc.com

### ISSUE THREAD

**Issue by ascent08** [StopModReposts/Illegal-Mod-Sites#478]
**What site do you want to be added?**
[https://mcmodspc.com](url)

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft

**Do you have anything else worth mentioning?**

**Comment by Brandonbr1** [comment]
does not repost mods it links back to the original download

but it does redistribute [OptiFine](https://optifine.net/) and Forge downloads
