### ISSUE TITLE
New site to add: hdpackmod.com

### ISSUE THREAD

**Issue by SteveKunG** [StopModReposts/Illegal-Mod-Sites#489]
**What site do you want to be added?**
https://hdpackmod.com/

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft

**Do you have anything else worth mentioning?**
They reposted my mod, [Fish of Thieves](https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves).
https://hdpackmod.com/fish-of-thieves-mod/

**Comment by Brandonbr1** [comment]
clicked on Void Totem and it linked backed to the original but it uses cutx.me url shortener  when using it
