### ISSUE TITLE
New site to add: [https://www.filehorse.com/]

### ISSUE THREAD

**Issue by Brandonbr1** [StopModReposts/Illegal-Mod-Sites#501]
**What site do you want to be added?**

https://www.filehorse.com/

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft

**Comment by GEOEGII555** [comment]
It reposts computer software, not mods
![изображение](https://user-images.githubusercontent.com/57674559/180179402-c1afd04e-0849-4c3d-a155-11ca205bb09a.png)
