### ISSUE TITLE
New site to add: [https://mcmodspc.com]

### ISSUE THREAD

**Issue by Trhod17** [StopModReposts/Illegal-Mod-Sites#510]
**What site do you want to be added?**
I want https://mcmodspc.com to be added to the list

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft

**Comment by TelepathicGrunt** [comment]
seconded. They are reposting my mod without permission:
https://mcmodspc.com/repurposed-structures-forge/
