### ISSUE TITLE
New site to add: https://faithful.team

### ISSUE THREAD

**Issue by luciobortoletto** [StopModReposts/Illegal-Mod-Sites#535]
**What site do you want to be added?**
https://faithful.team

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft

**Do you have anything else worth mentioning?**
This "faithful" resource pack website is not official (the real one is https://www.faithfulpack.net) and distributes stolen textures. More information here: https://www.faithfulpack.net/about. (Sorry for the bad english, I'm not English).

**Comment by Raft08** [comment]
Yep, just joined the server of the fake Faithful. They ban everyone that is trying to say that is a fake discord server
