### ISSUE TITLE
New site to add: cursefire.com

### ISSUE THREAD

**Issue by berrysauce** [StopModReposts/Illegal-Mod-Sites#541]
Check if it's related to Overwolf. Has the footer, but that can also just be copied.

**Comment by RacoonDog** [comment]
i asked a member of the curseforge community support team, it's a ripoff that is not affiliated with overwolf
they're already aware of its existence too

**Comment by berrysauce** [comment]
> i asked a member of the curseforge community support team, it's a ripoff that is not affiliated with overwolf
> 
> they're already aware of its existence too

Thanks for the quick help @RacoonDog! Could you please attach a screenshot of the support team's answer?

**Comment by Brandonbr1** [comment]
> i asked a member of the curseforge community support team, it's a ripoff that is not affiliated with overwolf they're already aware of its existence too

Yeah using a who is service curseforge is registered under Amazon registers 

Where as curse fire is registered under dnspod inc 

So it is likely that curse fire is not official

**Comment by berrysauce** [comment]
> > i asked a member of the curseforge community support team, it's a ripoff that is not affiliated with overwolf they're already aware of its existence too
> 
> 
> 
> Yeah using a who is service curseforge is registered under Amazon registers 
> 
> 
> 
> Whereas curse fire is registered under dns pod inc 
> 
> 
> 
> And also other quite important info is missing link technical contact and it even says on behalf of overwolf see for your self
> 
> 
> 
> https://www.whois.com/whois/cursefire.com
> 
> 
> 
> 
> 
> https://www.whois.com/whois/curseforge.com
> 
> So it is likely that curse fire is not official 
> 
> 
> 
> 

Good idea 👍 thanks!
