### ISSUE TITLE
New site to add: [https://mcleaks.net/]

### ISSUE THREAD

**Issue by Brandonbr1** [StopModReposts/Illegal-Mod-Sites#545]
**What site do you want to be added?**
https://mcleaks.net/

It claims to allow you to get free Minecraft to bypass the  accounts login thing with their auth app you can install 

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft 

**Do you have anything else worth mentioning?**
Most likely spyware

**Comment by Brandonbr1** [comment]
mcleaks.io was another that used to exist but does not anymore links to sus website now but it may be affected with mcleaks.net forgot to mention that

**Comment by berrysauce** [comment]
@Brandonbr1 Please use https://report.stopmodreposts.org/forms/report to report sites. We no longer accept reports (additions) via issues.

**Comment by Brandonbr1** [comment]
> Member

ok can you transfer it because i can't get pass the Captcha
