### ISSUE TITLE
What is this, how does it work, and what info does it collect about me?

### ISSUE THREAD

**Issue by allanonmage** [StopModReposts/Illegal-Mod-Sites#565]
I use several Serelium mods, and found this in the Collective mod's config file, which is his main support library:

	// Please check out https://stopmodreposts.org/ for more information on why this feature exists.
	"enableAntiRepostingCheck": true,

Your page and Github don't explain what this does or why as a server owner I would want to keep this enabled.  I suspect it's some kind of telemetry or phone-home function, but have no idea.

**Comment by berrysauce** [comment]
Hey @allanonmage 

I don't have a complete insight on what this flag enables in the background, but I believe there was some talk about verifying the file's download origin (URL) and checking if it's coming from a verified source or from a reposting site, which could then trigger a warning for the user.

I can't ensure anything, as I don't have any insight in the source code of the mod, but from the StopModReposts side, there are no privacy-concerns for you or your users. Our services do not track anything.

If you're still concerned, I recommend contacting the mod author. We do not have any active agreements with them.

**Comment by berrysauce** [comment]
Your question was, as far as I understood, explicitly about what that flag (`"enableAntiRepostingCheck": true`) does. As I did not write that code and am not in contact with the author, I do not know what it does.

If you're asking what _**we**_ do, why ask:
> Your page and Github don't explain what this does

If you had taken a look at our page and GitHub, you would've seen, that we maintain a list of "reposting" sites, which repost mods for popular games, without the permission of the mod author. Our services, in this case most likely our API (which is by the way also a public GitHub repository, to be precise this one) serves this list in different formats. That's it.
