### ISSUE TITLE
Any non-Minecraft sites currently being accepted?

### ISSUE THREAD

**Issue by skrrt** [StopModReposts/Illegal-Mod-Sites#67]
There are a lot of games out there that support mods made by the community besides Minecraft, and even for those games there are plenty of sites that illegally redistribute mods made by other sites. Sometimes they might even make their own mods that are incredibly low-quality (BeamNG.drive comes to mind as an example of a game suffering from these sites).

Any chance that these would be covered in the future for other games?

**Comment by bilde2910** [comment]
This sounds like a good idea in itself. Mod reuploads for other games doesn't make copyright infringement any less illegal, and that's what we're here to fight anyway.

I'll have to wait for @coolsquid and/or @VictiniX888 to have a say in the matter too. I just barely missed you on IRC and saw your messages a minute after you left, but from what I can see, BeamNG.drive has its own official mod hosting site, right? I came across [this site](http://www.beamng.com/resources/) on BeamNG.com; is this where modders would usually upload their mods?

**Comment by VictiniX888** [comment]
I remember coolsquid talked about wanting to also cover Skyrim as well, but decided not to due to not knowing the modding community well enough

I agree with bilde here, we should cover other games as well. It initially sounded somewhat difficult to do (because we don't know much about other modding communities, therefore probably don't even know what site is the original site and which are reposts). We *are* going to need help from modders from other games, so there's that

**Comment by coolsquid** [comment]
> I remember coolsquid talked about wanting to also cover Skyrim as well, but decided not to due to not knowing the modding community well enough

That would be correct, yes. I'm all in for opening for non-MC sites, but that will require help from people who know the communities in question, and will also require some effort on our side. We'll probably have to create separate lists for each modding community, as a single list would simply become too large and hard to navigate. I'd suggest we appoint a moderator for each list (unless any of you want to manage all of them), as we have limited capacity ourselves.

**Comment by Texenox** [comment]
> I just barely missed you on IRC and saw your messages a minute after you left, but from what I can see, BeamNG.drive has its own official mod hosting site, right? I came across this site on BeamNG.com; is this where modders would usually upload their mods?

You got it. That's currently being worked on as an accessible alternative to the forums.

If I get the time, I should be able to go on the BNG.d forums to open a discussion thread for this. I'd be glad to use the feedback given for it to help document sites for it.

**Comment by bilde2910** [comment]
Hi again, @Texenox ! Did you manage to get something posted on the forums? It would be interesting to see how the community would respond to this. No need to hurry, just checking in on how it goes :-)

**Comment by Flipp3rrr** [comment]
Just curious but are there any updates on this suggestion?

**Comment by bilde2910** [comment]
There was a discussion about this on the Discord a little while ago. Current consensus is that expanding to multiple games is a good idea, but the primary focus of the project is to expand reach within the Minecraft community first. Being able to support other games depends a lot on whether we have people familiar with the other games in question. Most of us are Minecraft players, and aren't familiar enough with, or necessarily motivated for, keeping track of mod reposts for other games. Getting people into our community who would be willing to keep track of reposts for other specific games would help here.

**Comment by AlexejheroYTB** [comment]
Hey, Subnautica modder, mod manager developer and community administrator here.

In the Subnautica community, or main mod sharing website is https://nexusmods.com. They provide a small amount of income for each download. 

Recently we've had a lot of websites illegally redistributing mods. To clarify, I don't mean just MIT/GPL mods. I mean ALL MODS. Including mods that do not allow redistribution.

It would be nice to get Subnautica (and Subnautica Below Zero) involved in this project.

I would be willing to help.

@bilde2910

**Comment by AlexejheroYTB** [comment]
bump

**Comment by berrysauce** [comment]
**Support for other games added** - https://discordapp.com/channels/463457129588850699/463457453523206154/646833913204965417
