### ISSUE TITLE
Mc Youtube Re-Uploader

### ISSUE THREAD

**Issue by mandm635** [StopModReposts/Illegal-Mod-Sites#77]
This site, [www.mineandcraft.com](www.mineandcraft.com), seems to be reposting Minecraft Youtube videos. Not sure, it may be streaming from Youtube but the layout seems different than a normal embedded video.

**Comment by VictiniX888** [comment]
Um, @bilde2910 @coolsquid do we accept additions for videos?

**Comment by deframet** [comment]
I think that's more phishing website that a repost site.

**Comment by bilde2910** [comment]
The videos themselves are embedded from YouTube, but I agree that this is likely a phishing site. Google may want to know about this, however, they don't seem to accept any requests that does not concern their own site directly in any way.

**Comment by mandm635** [comment]
Should a ftc report be made?

**Comment by mandm635** [comment]
Or maybe this?

https://www.google.com/safebrowsing/report_phish/

**Comment by bilde2910** [comment]
Thanks for the link! I sent them a report.

**Comment by mandm635** [comment]
Cool, post here if you get anything back.

**Comment by jtrent238** [comment]
Its embedded from youtube.

**Comment by Cazsius** [comment]
Nothing Further Required here. Report was sent.
