### ISSUE TITLE
Reposter?

### ISSUE THREAD

**Issue by mandm635** [StopModReposts/Illegal-Mod-Sites#84]
[http://minecraftmapdownloads.com/](http://minecraftmapdownloads.com/)

Requires you to share on twitter before downloading maps, not sure if this is reposting but thought I would check.

**Comment by jtrent238** [comment]
The creator of the map uploads it to the site so no.

**Comment by AlexejheroYTB** [comment]
This URL is no longer valid, so the issue can safely be closed.
