### ISSUE TITLE
parcraftmc

### ISSUE THREAD

**Issue by SupremeMortal** [StopModReposts/Illegal-Mod-Sites#97]
I don't know if you noticed but the reason this website has so many downloads is because you stumbled across a Technic Solder installation. This is simply a modpack repository and should be hidden but I doubt the intention of it was to cause any harm. http://solder.parcraftmc.com proves it.

**Comment by bilde2910** [comment]
This issue was apparently lost to time. It doesn't appear to pose any threat now, and I doubt the intention of this site was to distribute mods. Closing.
