### ISSUE TITLE
minecraftsix

### ISSUE THREAD

**Issue by Axelen123** [StopModReposts/Illegal-Mod-Sites#98]
I think minecraftsix.com is reposting mods. I dont know if it has any malware but it seems like a site which reposts mods

**Comment by willies952002** [comment]
Here's my two cents:
minecraftsix is a bit of a tricky site, they might create a post about the mod, which may or may not just be a copy-paste of what's on MCF, etc., but the mod files themselves are not hosted on the minecraftsix website last I checked, but are linked to/downloadable from one of the mod developer's authorized sources, such Curse, MCF, etc. However, they don't link to the page, but to the file directly, which is what makes it a tricky site to actually classify.

**Comment by jtrent238** [comment]
This one links to MCF
[](http://minecraftsix.com/iron-chests-mod/)

**Comment by gdavid04** [comment]
It also reposts resource packs, maps and one command creations. 9minecraft does the same

**Comment by Gamebuster19901** [comment]
This should be added immediately. They are misrepresenting versions. They are saying that the mod "Chop down updated" has a 1.13 version even though 1.13 is not out. http://minecraftsix.com/chop-down-updated-mod/

**Comment by jtrent238** [comment]
It still links to curseforge page.

**Comment by jtrent238** [comment]
[Minecraft Forge 1.13](https://github.com/MinecraftForge/MinecraftForge/tree/1.13.x) will be found [here](https://github.com/MinecraftForge/MinecraftForge/tree/1.13.x).

**Comment by Gamebuster19901** [comment]
The fact that it links to curseforge doesn't matter. It still violates [15 U.S. Code § 52 - Dissemination of false advertisements](https://www.gpo.gov/fdsys/pkg/USCODE-2011-title15/pdf/USCODE-2011-title15-chap2-subchapI-sec52.pdf2) and [16 CFR Part 238 - GUIDES AGAINST BAIT ADVERTISING](https://www.gpo.gov/fdsys/pkg/CFR-2000-title16-vol1/xml/CFR-2000-title16-vol1-part238.xml)

**Comment by Gamebuster19901** [comment]
Also violates 15 U.S. Code § 1125 - False designations of origin, false descriptions, and dilution forbidden
